### ISSUE TITLE
DATA

### ISSUE THREAD

**Issue by Amaya-yy** [jin-taiyu/Bnalyser#2]
作者，你好！请问可以提供该项目的数据吗？感谢~

**Comment by jin-taiyu** [comment]
您好！请问您说的具体是什么数据？

**Comment by Amaya-yy** [comment]
你好～就是这个项目的原始数据(训练集，验证集以及测试)，方便加个联系方式吗








且笑
***@***.***


---Original---
From: "Jin ***@***.***&gt;
Date: Thu, Oct 17, 2024 20:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jin-taiyu/Bnalyser] DATA (Issue #2)




 
您好！请问您说的具体是什么数据？
