### ISSUE TITLE
您好！请问您说的具体是什么数据？

### ISSUE THREAD

**Issue by Amaya-yy** [jin-taiyu/Bnalyser#3]
您好！请问您说的具体是什么数据？

_Originally posted by @jin-taiyu in https://github.com/jin-taiyu/Bnalyser/issues/2#issuecomment-2419347134_

**Comment by Amaya-yy** [comment]
> ```
>           您好！请问您说的具体是什么数据？
> ```
> 
> _Originally posted by @jin-taiyu in [#2 (comment)](https://github.com/jin-taiyu/Bnalyser/issues/2#issuecomment-2419347134)_

因为我在data/analyse.json这个路径下看到的数据很少（这是原始数据对吗，望指教~）

**Comment by jin-taiyu** [comment]
若您所指为模型的**带标签训练数据**，该数据应存放于 ./train 目录中。但鉴于数据量较大，故未进行上传。若您需要这些数据，请告知您的邮箱或其他联系方式，我可以将数据发送给您。

**Comment by Amaya-yy** [comment]
真的太感谢您啦~那方便加个微信吗，(VX号：yang992220)

**Comment by Amaya-yy** [comment]
真的太感谢您啦~那方便加个微信吗，(VX号：yang992220)
